import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "@/styles/globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="es">
      <head>
        {/* <StructuredData /> */}
      </head>
      <body className={`${manrope.variable}`}>
        {children}
        <Script id="add-loaded-class" strategy="afterInteractive">
          {`document.documentElement.classList.add('loaded');`}
        </Script>
      </body>
    </html>
  );
}
